## Remember that the solutions need to be saved int variable provided.

In [2]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [3]:
sol1 = np.random.randint(100,size=(10,10))
print(sol1)
print(np.min(sol1))
print(np.max(sol1))


[[40  5 63  5 93 71 26 62 18 32]
 [55 15 91 43 80 80 63 42 26 18]
 [94 34 95 26 15 87 28 13 35  1]
 [48 72 84 40  4 58 31  4 65 95]
 [86 50 65 76 35 66 25 45 84 94]
 [95 74 12 33 65 31 22 77 27 33]
 [15 31 78 85 34 76 56 32 83 26]
 [51  8 58  6 64 77 39 89 24 36]
 [98 23 89 67 90 54 15 49 86 11]
 [47 20 28 47  8 36 57 89 70  1]]
1
98


In [4]:
assert sol1.shape == (10,10)

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [5]:
sol2 = np.ones((10,10))
sol2[1:-1,1:-1] = 0
print(sol2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
assert sol2.shape == (10,10)
assert sol2[0].all() == 1
assert sol2[:,0].all() == 1
assert sol2[1][1] == 0
assert sol2[2][2] == 0
assert sol2[3][3] == 0
assert sol2[4][4] == 0
assert sol2[1][2] == 0
assert sol2[2][3] == 0
assert sol2[3][4] == 0
assert sol2[4][5] == 0

**34. How to get all the dates corresponding to the month of July 2016**

In [7]:
sol3 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(sol3)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [8]:
assert sol3.shape == (31,)
assert type(sol3[0]) is np.datetime64

**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [13]:
#2 points
sol41 = np.random.randint(50,size=(10,10))
sol42 = np.random.randint(50,size=(10,10))
comparisson = np.allclose(sol41,sol42)
print(comparisson)

False


In [ ]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

**72. How to swap two rows of an array?** 

In [15]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])
sol5
sol5[[0, 1]] = sol5[[1, 0]]
sol5



array([[4, 5, 6],
       [1, 2, 3]])

In [16]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [31]:
sol6 = 0
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(moving_average(arr, n=3))

[2. 3. 4. 5. 6. 7. 8. 9.]


In [32]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5

TypeError: 'int' object is not subscriptable